services:
  nest-demo:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env.development
    environment:
      NODE_ENV: docker
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: modulo4
    depends_on:
      - postgres
    networks:
      - app-networks

  postgres:
    image: postgres:16
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: modulo4
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-networks
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  
volumes:
  postgres-data:

networks:
  app-networks:

# services:
#   nest-demo:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "3000:3000"
#     volumes:
#       - .:/app
#     env_file:
#       - .env.development
#     environment:
#       NODE_ENV: docker
#     depends_on:
#       - postgres
#     networks:
#       - app-networks

#   postgres:
#     image: postgres:16
#     ports:
#       - '5432:5432'
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: modulo4
#     volumes:
#         - postgres-data:/var/lib/postgresql/data
#     networks:
#       - app-networks
  
# volumes:
#   postgres-data:

# networks:
#   app-networks:
    